import type {
  AuditSink,
  FactStore,
  Finding,
  FindingStore,
  LlmProvider
} from "@software-analysis/core";
import { createId } from "@software-analysis/core";

import { redactSensitiveText } from "../evidence/text-redaction.js";

export interface LlmEnrichmentServiceDependencies {
  audit: AuditSink;
  facts: FactStore;
  findings: FindingStore;
  provider?: LlmProvider;
}

export interface EnrichInput {
  projectId: string;
  target: "endpoint_summary" | "workflow_naming" | "entity_description" | "documentation_polish";
  promptVersion?: string;
}

export interface EnrichResult {
  status: "disabled" | "blocked" | "succeeded" | "failed";
  provider: string;
  model: string;
  prompt_version: string;
  finding_ids: string[];
  redaction_status: "redacted" | "blocked";
  warnings: string[];
}

export class DisabledLlmProvider implements LlmProvider {
  readonly provider = "disabled";
  readonly model = "none";

  complete(): Promise<never> {
    return Promise.reject(new Error("LLM provider is disabled"));
  }
}

export class FakeLlmProvider implements LlmProvider {
  readonly provider = "fake";
  readonly model = "fake-structured-output";

  complete(): Promise<{
    provider: string;
    model: string;
    content: string;
    structured: Record<string, unknown>;
  }> {
    const structured = {
      annotations: [
        {
          title: "Candidate summary",
          description: "Generated by fake provider for deterministic tests."
        }
      ]
    };
    return Promise.resolve({
      provider: this.provider,
      model: this.model,
      content: JSON.stringify(structured),
      structured
    });
  }
}

export class LlmEnrichmentService {
  constructor(private readonly deps: LlmEnrichmentServiceDependencies) {}

  async enrich(input: EnrichInput): Promise<EnrichResult> {
    const provider = this.deps.provider ?? new DisabledLlmProvider();
    const promptVersion = input.promptVersion ?? `phase5-${input.target}-v1`;
    if (provider instanceof DisabledLlmProvider) {
      await this.audit(input.projectId, "llm.disabled", provider, promptVersion, "redacted", {
        target: input.target
      });
      return {
        status: "disabled",
        provider: provider.provider,
        model: provider.model,
        prompt_version: promptVersion,
        finding_ids: [],
        redaction_status: "redacted",
        warnings: ["llm_provider_disabled"]
      };
    }

    const context = await this.context(input.projectId, input.target);
    const redacted = redactSensitiveText(context);
    if (redacted.redacted) {
      await this.audit(input.projectId, "llm.blocked", provider, promptVersion, "blocked", {
        target: input.target,
        reason: "sensitive_candidate_detected"
      });
      return {
        status: "blocked",
        provider: provider.provider,
        model: provider.model,
        prompt_version: promptVersion,
        finding_ids: [],
        redaction_status: "blocked",
        warnings: ["sensitive_candidate_detected"]
      };
    }

    try {
      const response = await provider.complete({
        project_id: input.projectId,
        prompt_version: promptVersion,
        messages: [
          {
            role: "system",
            content:
              "Return only structured annotations. Do not invent facts and do not raise confidence."
          },
          { role: "user", content: redacted.value }
        ],
        response_schema: {
          type: "object",
          properties: {
            annotations: { type: "array" }
          },
          required: ["annotations"]
        },
        timeout_ms: 30_000
      });
      const annotations = annotationsFrom(response.structured ?? parseJsonObject(response.content));
      const findingIds: string[] = [];
      const evidenceRefs = await this.evidenceRefs(input.projectId);
      for (const annotation of annotations) {
        const finding: Finding = {
          id: createId("find"),
          project_id: input.projectId,
          kind: "llm_annotation",
          title: annotation.title,
          description: annotation.description,
          confidence: 0.3,
          evidence_refs: evidenceRefs,
          data: {
            target: input.target,
            provider: response.provider,
            model: response.model,
            prompt_version: promptVersion,
            status: "candidate"
          },
          created_at: new Date().toISOString()
        };
        await this.deps.findings.save(finding);
        findingIds.push(finding.id);
      }
      await this.audit(input.projectId, "llm.succeeded", provider, promptVersion, "redacted", {
        target: input.target,
        annotation_count: annotations.length
      });
      return {
        status: "succeeded",
        provider: response.provider,
        model: response.model,
        prompt_version: promptVersion,
        finding_ids: findingIds,
        redaction_status: "redacted",
        warnings: []
      };
    } catch (error) {
      await this.audit(input.projectId, "llm.failed", provider, promptVersion, "redacted", {
        target: input.target,
        error: error instanceof Error ? error.message : String(error)
      });
      return {
        status: "failed",
        provider: provider.provider,
        model: provider.model,
        prompt_version: promptVersion,
        finding_ids: [],
        redaction_status: "redacted",
        warnings: ["llm_provider_error"]
      };
    }
  }

  private async context(projectId: string, target: EnrichInput["target"]): Promise<string> {
    const facts = await this.deps.facts.listByProject(projectId);
    const selected = facts
      .filter((fact) => targetFacts(target).includes(fact.kind))
      .slice(0, 50)
      .map((fact) => ({
        kind: fact.kind,
        evidence_refs: fact.evidence_refs,
        data: fact.data
      }));
    return JSON.stringify({ target, facts: selected });
  }

  private async evidenceRefs(projectId: string): Promise<string[]> {
    const facts = await this.deps.facts.listByProject(projectId);
    const refs = [...new Set(facts.flatMap((fact) => fact.evidence_refs))];
    return refs.length > 0 ? refs : ["ev_placeholder"];
  }

  private async audit(
    projectId: string,
    action: string,
    provider: LlmProvider,
    promptVersion: string,
    redactionStatus: "redacted" | "blocked",
    metadata: Record<string, unknown>
  ): Promise<void> {
    await this.deps.audit.append({
      id: createId("audit"),
      project_id: projectId,
      actor: "service",
      action,
      target_type: "llm",
      target_id: `${provider.provider}:${provider.model}`,
      metadata: {
        ...metadata,
        provider: provider.provider,
        model: provider.model,
        prompt_version: promptVersion,
        redaction_status: redactionStatus
      },
      created_at: new Date().toISOString()
    });
  }
}

function targetFacts(target: EnrichInput["target"]): string[] {
  if (target === "workflow_naming") {
    return ["workflow"];
  }
  if (target === "entity_description") {
    return ["business_entity"];
  }
  return ["api_endpoint", "workflow", "business_entity"];
}

function parseJsonObject(content: string): Record<string, unknown> {
  const parsed = JSON.parse(content) as unknown;
  if (typeof parsed !== "object" || parsed === null || Array.isArray(parsed)) {
    throw new Error("LLM response must be a JSON object");
  }
  return parsed as Record<string, unknown>;
}

function annotationsFrom(value: Record<string, unknown>): { title: string; description: string }[] {
  const annotations = value.annotations;
  if (!Array.isArray(annotations)) {
    throw new Error("LLM response missing annotations");
  }
  return annotations.map((annotation) => {
    if (typeof annotation !== "object" || annotation === null || Array.isArray(annotation)) {
      throw new Error("LLM annotation must be an object");
    }
    const candidate = annotation as Record<string, unknown>;
    return {
      title: typeof candidate.title === "string" ? candidate.title : "LLM annotation",
      description: typeof candidate.description === "string" ? candidate.description : ""
    };
  });
}
